import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
// import { ThemeSwitcher } from "@/components/ThemeSwitcher";
import SidebarNav from "./SidebarNav";
import RouteGuardClient from "./RouteGuardClient";
import ToastProvider from "@/components/ToastProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <ToastProvider>
          <div className="min-h-screen grid grid-cols-[240px_1fr]">
            <aside className="border-r p-4">
            <a href="/" className="inline-block font-semibold mb-4 text-[var(--color-brand-700)] border rounded px-3 py-2 hover:bg-[var(--muted-bg)]" aria-label="Go to homepage">FleetOS</a>
            <SidebarNav />
            <div className="mt-6 text-xs text-[var(--muted)]">Theme switcher temporarily disabled</div>
            </aside>
            <main>
              <RouteGuardClient>{children}</RouteGuardClient>
            </main>
          </div>
        </ToastProvider>
      </body>
    </html>
  );
}

function ThemeSwitcher() {
  function setTheme(name: 'light' | 'dark') {
    if (name === 'dark') {
      document.documentElement.style.setProperty('--background', '#0a0a0a');
      document.documentElement.style.setProperty('--foreground', '#ededed');
    } else {
      document.documentElement.style.setProperty('--background', '#ffffff');
      document.documentElement.style.setProperty('--foreground', '#0f172a');
    }
  }
  return (
    <div className="grid gap-2">
      <div className="text-xs text-[var(--muted)]">Theme</div>
      <div className="flex gap-2">
        <button className="border px-2 py-1 rounded" onClick={() => setTheme('light')}>Light</button>
        <button className="border px-2 py-1 rounded" onClick={() => setTheme('dark')}>Dark</button>
      </div>
    </div>
  );
}
